name: CI

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checking if Python is installed
        run: python3 --version

      - name: Checking if PIP is installed
        run: python3 -m pip --version

      - name: Installing Ansible
        run: python3 -m pip install --user ansible

      - name: Create Test Playbook
        run: |
          cd ..
          mkdir -p playbook
          cd playbook
          mkdir roles
          cp -r ../my_apache ./roles/
          cp ./roles/my_apache/tests/* .

      - name: Run Test Playbook
        run: cd ../playbook && ansible-playbook test.yml
