name: CI

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checking if Python is installed
        run: python3 --version

      - name: Checking if PIP is installed
        run: python3 -m pip --version

      - name: Installing Ansible
        run: python3 -m pip install --user ansible

      - name: Create Playbook
        run: |
          mkdir -p ./playbook/roles
          mv !(playbook) ./playbook/roles
          ls


